//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int contactId { get; set; }
        public string name { get; set; }
        public string Email { get; set; }
        public int mobile { get; set; }
        public string subject { get; set; }
    }
}
