//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user_SignUp
    {
        
        public int id { get; set; }
        [Required(ErrorMessage = "This field is required!!")]
        public string username { get; set; }
        [Required(ErrorMessage = "This field is required!!")]
        public string password { get; set; }
        public string loginerrorMessage { get; set; }       

        [Compare("password")]
        public string confirmpassword { get; set; }
    }
}
